### PR TITLE
fix: forbidden String.format() method invocations in main source files

### LINKED ISSUE #466: [BUG] String.format() uses the default system locale
**What is the bug?**
A clear and concise description of the bug.

Issue: String.format() uses the default system locale, which can cause:

- Inconsistent behavior across different systems/locales
- Potential internationalization bugs in distributed environments
- Unpredictable formatting in production

Warnings during build example: "Forbidden method invocation: java.lang.String#format(java.lang.String,java.lang.Object[]) [Uses default locale] in org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer (KNN80DocValuesConsumer.java:62)"

**How can one reproduce the bug?**

**What is the expected behavior?**

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

### PR DESCRIPTION
**Pull request by tomkdgun**
### Description

Issue: String.format() uses the default system locale, which can cause:
- Inconsistent behavior across different systems/locales
- Potential internationalization bugs in distributed environments
- Unpredictable formatting in production

1. Fixed all forbidden `String.format()` method invocations in main source files by adding `Locale.ROOT` parameter or using parameterized logging. Example entry during build before fix: "Forbidden method invocation: java.lang.String#format(java.lang.String,java.lang.Object[]) [Uses default locale] in org.opensearch.knn.index.codec.KNN80Codec.KNN80DocValuesConsumer (KNN80DocValuesConsumer.java:62)"
2. Remove duplicated logger from files below, one added from Lombok (log), and manually added (logger)
- src/main/java/org/opensearch/knn/index/KNNSettings.java
- src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java

### Related Issues
Resolves https://github.com/opensearch-project/opensearch-jvector/issues/466

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [x] Commits are signed per the DCO using `--signoff`.
- [x] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by WojciechKrakowiak — APPROVED** [review]
Looks good to me.
I was wondering about the usage of Locale.ROOT for english messaged, but the goal is injecting the variables into string. Moreover, the ROOT is for sure better for english messages than a default one, that could be any locale.

File: src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java [hunk 1]
```diff
@@ -53,13 +49,13 @@ public void addBinaryField(FieldInfo field, DocValuesProducer valuesProducer) th
             stopWatch.stop();
             long time_in_millis = stopWatch.totalTime().millis();
             KNNGraphValue.REFRESH_TOTAL_TIME_IN_MILLIS.set(KNNGraphValue.REFRESH_TOTAL_TIME_IN_MILLIS.getValue() + time_in_millis);
-            logger.warn("Refresh operation complete in " + time_in_millis + " ms");
+            log.warn("Refresh operation complete in " + time_in_millis + " ms");
```
Comment (reta) [inline src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java]:
```suggestion
            log.warn("Refresh operation complete in {} ms", time_in_millis);
```

File: src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java [hunk 2]
```diff
@@ -89,7 +85,7 @@ public void merge(MergeState mergeState) {
                     stopWatch.stop();
                     long time_in_millis = stopWatch.totalTime().millis();
                     KNNGraphValue.MERGE_TOTAL_TIME_IN_MILLIS.set(KNNGraphValue.MERGE_TOTAL_TIME_IN_MILLIS.getValue() + time_in_millis);
-                    logger.warn("Merge operation complete in " + time_in_millis + " ms");
+                    log.warn("Merge operation complete in " + time_in_millis + " ms");
```
Comment (reta) [inline src/main/java/org/opensearch/knn/index/codec/KNN80Codec/KNN80DocValuesConsumer.java]:
```suggestion
                    log.warn("Merge operation complete in {} ms", time_in_millis);
```

**Comment by reta** [comment]
Thanks @tomkdgun , the change makes sense to me. A few minor comments, could you please add entry to CHANGELOG.md since we are changing production code? Thank you

**Review by reta — APPROVED** [review]
