### PR TITLE
Fix flaky org.opensearch.knn.index.codec.jvector.KNNJVectorTests.testJVectorKnnIndex_mergeEnabled

### LINKED ISSUE #281: [BUG] Fix flaky org.opensearch.knn.index.codec.jvector.KNNJVectorTests.testJVectorKnnIndex_mergeEnabled
Example: https://github.com/opensearch-project/opensearch-jvector/actions/runs/21951790222/job/63404351717

### PR DESCRIPTION
**Pull request by reta**
### Description
Fix flaky org.opensearch.knn.index.codec.jvector.KNNJVectorTests.testJVectorKnnIndex_mergeEnabled

### Related Issues
Resolves #281

### Check List
- [ ] New functionality includes testing.
- [ ] New functionality has been documented.
- [ ] API changes companion pull request [created](https://github.com/opensearch-project/opensearch-api-specification/blob/main/DEVELOPER_GUIDE.md).
- [ ] Commits are signed per the DCO using `--signoff`.
- [ ] Public documentation issue/PR [created](https://github.com/opensearch-project/documentation-website/issues/new/choose).

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/k-NN/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

File: src/main/java/org/opensearch/knn/common/KNNConstants.java [hunk 1]
```diff
@@ -108,6 +108,10 @@ public class KNNConstants {
     public static final String METHOD_PARAMETER_LEADING_SEGMENT_MERGE_DISABLED = "advanced.leading_segment_merge_disabled";
     public static final boolean DEFAULT_LEADING_SEGMENT_MERGE_DISABLED = false;
 
+    // Parameters that only affect search
+    public static final String METHOD_PARAMETER_ENTRY_POINT_SELECTION_DISABLED = "advanced.entry_point_selection_disabled";
+    public static final Boolean DEFAULT_ENTRY_POINT_SELECTION_DISABLED = false;
```
Comment (akash-shankaran) [inline src/main/java/org/opensearch/knn/common/KNNConstants.java]: please add a comment here, that entry point selection is only for tests.

File: src/test/java/org/opensearch/knn/index/codec/jvector/KNNJVectorTests.java [hunk 2]
```diff
@@ -373,6 +384,71 @@ public void testJVectorKnnIndex_mergeEnabled() throws IOException {
         }
     }
 
+    @Test
+    public void testJVectorKnnIndex_mergeDisabled() throws IOException {
+        int k = 3; // The number of nearest neighbours to gather
+        int totalNumberOfDocs = 10;
```
Comment (akash-shankaran) [inline src/test/java/org/opensearch/knn/index/codec/jvector/KNNJVectorTests.java]: should this also be 1000 docs?

**Comment by reta** [comment]
> Maybe I am missing something here, but if entry point selection is TRUE, then the code selects a default entry point (0,0). If it is FALSE, then the library picks the entry point.

I will try to clarify the reasoning here. By default, the entry point is selected more or less "randomly" (due to the concurrent graph construction). It corresponds to "entry point selection is ENABLED", this is what we should stick to. Consequently, the fixed value (0, 0) corresponds to "entry point selection is DISABLED".

The setting is inverse of that, `entryPointSelectionDisabled`. since we want it to be set **only when default selection should not take place**.  To rephrase what you said: if entry point selection is TRUE, then the code selects a "random" value (entryPointSelectionDisabled == false)

Hope it helps.

File: src/test/java/org/opensearch/knn/index/codec/jvector/KNNJVectorTests.java [hunk 3]
```diff
@@ -185,11 +186,11 @@ public void test_sorted_index() throws IOException {
         final String sortFieldName = "sorted_field";
         IndexWriterConfig indexWriterConfig = LuceneTestCase.newIndexWriterConfig();
         indexWriterConfig.setUseCompoundFile(false);
-        indexWriterConfig.setCodec(getCodec());
+        indexWriterConfig.setCodec(getCodec(DEFAULT_MINIMUM_BATCH_SIZE_FOR_QUANTIZATION, DEFAULT_LEADING_SEGMENT_MERGE_DISABLED, true));
```
Comment (reta) [inline src/test/java/org/opensearch/knn/index/codec/jvector/KNNJVectorTests.java]: See please https://github.com/opensearch-project/opensearch-jvector/issues/282#issuecomment-4170651567
